export type AssetCategory = 'Bonds' | 'Crypto' | 'Real Estate'

export type AssetRow = {
    asset: string,
    assetId: string,
    shareOfAsset: string,
    valuation: string,
    volume: string,
    marketValue: string,
    loan: string,
    chain: string,
    issuer: string,
    custodian: string,
    oracleSource: string,
    valuationDate: string,
}

export const ASSET_TABLE_DATA: Record<AssetCategory, AssetRow[]> = {
    "Bonds": [
        {
            asset: 'Government Bond 1',
            assetId: 'BOND001',
            shareOfAsset: '45%',
            valuation: '105%',
            volume: '2.5M',
            marketValue: '$125,000',
            loan: '$15,000',
            chain: 'Ethereum',
            issuer: 'US Treasury',
            custodian: 'State Street',
            oracleSource: 'Chainlink',
            valuationDate: 'Daily',
        },
        {
            asset: 'Corporate Bond 1',
            assetId: 'BOND002',
            shareOfAsset: '38%',
            valuation: '98%',
            volume: '1.8M',
            marketValue: '$95,000',
            loan: '$12,000',
            chain: 'Polygon',
            issuer: 'Apple Inc',
            custodian: 'BNY Mellon',
            oracleSource: 'Pyth',
            valuationDate: 'Daily',
        },
        {
            asset: 'Municipal Bond 1',
            assetId: 'BOND003',
            shareOfAsset: '22%',
            valuation: '102%',
            volume: '900K',
            marketValue: '$75,000',
            loan: '$8,500',
            chain: 'Ethereum',
            issuer: 'NYC Municipal',
            custodian: 'JPMorgan',
            oracleSource: 'Chainlink',
            valuationDate: 'Weekly',
        },
    ],
    "Crypto": [
        {
            asset: 'Bitcoin',
            assetId: 'BTC001',
            shareOfAsset: '65%',
            valuation: '95%',
            volume: '0.5 BTC',
            marketValue: '$200,000',
            loan: '$25,000',
            chain: 'Bitcoin',
            issuer: 'Bitcoin Network',
            custodian: 'Coinbase Custody',
            oracleSource: 'Chainlink',
            valuationDate: 'Real-time',
        },
        {
            asset: 'Ethereum',
            assetId: 'ETH001',
            shareOfAsset: '28%',
            valuation: '110%',
            volume: '12.5 ETH',
            marketValue: '$85,000',
            loan: '$18,000',
            chain: 'Ethereum',
            issuer: 'Ethereum Foundation',
            custodian: 'Fireblocks',
            oracleSource: 'Pyth',
            valuationDate: 'Real-time',
        },
        {
            asset: 'USDC',
            assetId: 'USDC001',
            shareOfAsset: '15%',
            valuation: '100%',
            volume: '50,000 USDC',
            marketValue: '$50,000',
            loan: '$5,000',
            chain: 'Ethereum',
            issuer: 'Centre',
            custodian: 'Circle',
            oracleSource: 'Chainlink',
            valuationDate: 'Real-time',
        },
    ],
    "Real Estate": [
        {
            asset: 'Real Estate 1',
            assetId: '98246278',
            shareOfAsset: '75%',
            valuation: '120%',
            volume: '5%',
            marketValue: '$50,000',
            loan: '$3,000',
            chain: 'Ethereum',
            issuer: 'Bitgo',
            custodian: 'Zodia Custody',
            oracleSource: 'Chainlink',
            valuationDate: 'Onchain',
        },
        {
            asset: 'Real Estate 2',
            assetId: '98246278',
            shareOfAsset: '56%',
            valuation: '120%',
            volume: '1000',
            marketValue: '$50,000',
            loan: '$3,000',
            chain: 'Canton Network',
            issuer: 'RWS',
            custodian: 'Zodia Custody',
            oracleSource: 'Chainlink',
            valuationDate: 'Onchain',
        },
        {
            asset: 'Real Estate 3',
            assetId: '98246278',
            shareOfAsset: '43%',
            valuation: '120%',
            volume: '0,1',
            marketValue: '$50,000',
            loan: '$3,000',
            chain: 'Ethereum',
            issuer: 'RWS',
            custodian: 'Zodia Custody',
            oracleSource: 'Chainlink',
            valuationDate: 'Onchain',
        },
        {
            asset: 'Real Estate 4',
            assetId: '98246278',
            shareOfAsset: '20%',
            valuation: '120%',
            volume: '1',
            marketValue: '$50,000',
            loan: '$3,000',
            chain: 'Ethereum',
            issuer: 'RWS',
            custodian: 'Zodia Custody',
            oracleSource: 'Chainlink',
            valuationDate: 'Onchain',
        },
    ],
}